# Change these first
owner: iqbalpb01 # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: Website
    url: https://beaglesecurity.com

  - name: API
    url: https://api.beaglesecurity.com/healthz

  - name: Blog
    url: https://beaglesecurity.com/blog

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /up
  logoUrl: https://cdn.beaglesecurity.com/maintenance/beagle_blue.svg
  name: System Status
  links:
    - rel: stylesheet
      href: https://cdn.beaglesecurity.com/maintenance/status.css
  favicon: https://cdn.beaglesecurity.com/maintenance/favicon.png
  faviconSvg: https://cdn.beaglesecurity.com/assets/logo/beagle-sidebar-icon.svg
  robotsText: "User-agent: * \n Disallow: /"
